### PR TITLE
Work on the Documentation page

### PR DESCRIPTION
**Pull request by paperclypse**
I added a brief introduction and started to add some context to the examples.

### CODE REVIEW

**Comment by wavebeem** [comment]
So I found out Netlify is making deploy previews still ( you can preview your branch here: https://5e70ee991b33980008790d76--1bit-ui.netlify.com/docs/ ) but GitHub is not showing them. Weird.

The changes look good, Though I think you can remove the "Basics" header now since introduction is so short and they kinda fit together.

I see what you mean about the wonkiness when editing the custom properties. If someone sets an empty string or invalid value it kinda goes to shit. I should probably add validation that they add a size or color value before actually updating it.

**Comment by wavebeem** [comment]
Also, not sure what you're using to edit the code, but I use the Prettier - Code Formatter plugin for VSCode and set it to format on save so that my HTML stays nice and tidy and it line wraps paragraphs for me.

**Comment by paperclypse** [comment]
I've just been using Atom, because I'm used to it. But I'm sure it has a Prettier - Code Formatter plugin. I'll look into it.

**Comment by paperclypse** [comment]
Do you have a Prettier config file that you use generally?

**Comment by wavebeem** [comment]
@paperclypse I just use the defaults :) they're very good. i'm so old i remember the days before prettier even had a single config option lol

**Comment by wavebeem** [comment]
OMG the netlify deploy preview UI showed back up in github!!!
image

**Pull request merged**
